"""initial schema

Revision ID: d8f047e5838b
Revises: 
Create Date: 2026-09-05 13:16:43.821042

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd8f047e5838b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cisa_kev',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('product', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_action', sa.Text(), nullable=False),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cisa_kev')),
    sa.UniqueConstraint('cve_id', name='uq_cisa_kev_cve')
    )
    op.create_index(op.f('ix_cisa_kev_cve_id'), 'cisa_kev', ['cve_id'], unique=False)
    op.create_table('compliance_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard', sa.String(length=64), nullable=False),
    sa.Column('control_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('finding_categories', sa.Text(), nullable=False),
    sa.Column('is_defensible', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_mappings')),
    sa.UniqueConstraint('standard', 'control_id', name='uq_compliance_standard_control')
    )
    op.create_index(op.f('ix_compliance_mappings_standard'), 'compliance_mappings', ['standard'], unique=False)
    op.create_table('cves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('cvss_vector', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('references', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cves'))
    )
    op.create_index(op.f('ix_cves_cve_id'), 'cves', ['cve_id'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('name', name=op.f('uq_organizations_name'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('threat_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('identifier', sa.String(length=120), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('indicators', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threat_intelligence'))
    )
    op.create_table('asset_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_asset_groups_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_groups'))
    )
    op.create_index(op.f('ix_asset_groups_tenant_id'), 'asset_groups', ['tenant_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_key', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('os_name', sa.String(length=128), nullable=True),
    sa.Column('os_version', sa.String(length=128), nullable=True),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('firmware_version', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.String(length=64), nullable=True),
    sa.Column('criticality', sa.String(length=32), nullable=False),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.Column('is_internet_facing', sa.Boolean(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('vulnerability_count', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_assets_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_asset_key'), 'assets', ['asset_key'], unique=True)
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_criticality'), 'assets', ['criticality'], unique=False)
    op.create_index(op.f('ix_assets_department'), 'assets', ['department'], unique=False)
    op.create_index(op.f('ix_assets_domain'), 'assets', ['domain'], unique=False)
    op.create_index(op.f('ix_assets_hostname'), 'assets', ['hostname'], unique=False)
    op.create_index(op.f('ix_assets_ip_address'), 'assets', ['ip_address'], unique=False)
    op.create_index(op.f('ix_assets_is_internet_facing'), 'assets', ['is_internet_facing'], unique=False)
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_authorized', sa.Boolean(), nullable=False),
    sa.Column('registrar', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_domains_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domains'))
    )
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=True)
    op.create_index(op.f('ix_domains_tenant_id'), 'domains', ['tenant_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=True),
    sa.Column('auth_ref', sa.String(length=255), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('events_json', sa.Text(), nullable=False),
    sa.Column('last_status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_integrations_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations'))
    )
    op.create_index(op.f('ix_integrations_tenant_id'), 'integrations', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('otp_secret', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_users_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('cve', sa.String(length=32), nullable=True),
    sa.Column('cwe', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('cvss_vector', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('product', sa.String(length=128), nullable=True),
    sa.Column('affected_versions', sa.Text(), nullable=False),
    sa.Column('fixed_versions', sa.Text(), nullable=False),
    sa.Column('cpe', sa.String(length=128), nullable=True),
    sa.Column('capec', sa.String(length=32), nullable=True),
    sa.Column('is_kev', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('references', sa.Text(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_vulnerabilities_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vulnerabilities')),
    sa.UniqueConstraint('fingerprint', name='uq_vulnerabilities_fingerprint')
    )
    op.create_index(op.f('ix_vulnerabilities_cve'), 'vulnerabilities', ['cve'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_cwe'), 'vulnerabilities', ['cwe'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_fingerprint'), 'vulnerabilities', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_tenant_id'), 'vulnerabilities', ['tenant_id'], unique=False)
    op.create_table('asset_group_members',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_group_members_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['asset_groups.id'], name=op.f('fk_asset_group_members_group_id_asset_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'group_id', name=op.f('pk_asset_group_members'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('previous_state', sa.Text(), nullable=False),
    sa.Column('new_state', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_audit_logs_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_notifications_tenant_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_preview', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_reports_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_reports_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_report_key'), 'reports', ['report_key'], unique=True)
    op.create_index(op.f('ix_reports_tenant_id'), 'reports', ['tenant_id'], unique=False)
    op.create_table('scan_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=False),
    sa.Column('cron_expression', sa.String(length=120), nullable=True),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('profile', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_scan_schedules_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_scan_schedules_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_schedules'))
    )
    op.create_index(op.f('ix_scan_schedules_tenant_id'), 'scan_schedules', ['tenant_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('profile', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('scope_confirmed', sa.Boolean(), nullable=False),
    sa.Column('safety_confirmed', sa.Boolean(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_scans_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_scans_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    op.create_index(op.f('ix_scans_requested_by'), 'scans', ['requested_by'], unique=False)
    op.create_index(op.f('ix_scans_scan_key'), 'scans', ['scan_key'], unique=True)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_index(op.f('ix_scans_tenant_id'), 'scans', ['tenant_id'], unique=False)
    op.create_table('subdomains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_responsive', sa.Boolean(), nullable=False),
    sa.Column('is_in_scope', sa.Boolean(), nullable=False),
    sa.Column('resolved_ip', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('fk_subdomains_domain_id_domains'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_subdomains_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subdomains'))
    )
    op.create_index(op.f('ix_subdomains_domain_id'), 'subdomains', ['domain_id'], unique=False)
    op.create_index(op.f('ix_subdomains_status'), 'subdomains', ['status'], unique=False)
    op.create_index(op.f('ix_subdomains_tenant_id'), 'subdomains', ['tenant_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_no', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('cvss_vector', sa.String(length=64), nullable=True),
    sa.Column('cve', sa.String(length=32), nullable=True),
    sa.Column('cwe', sa.String(length=32), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('affected_component', sa.String(length=255), nullable=True),
    sa.Column('detected_version', sa.String(length=64), nullable=True),
    sa.Column('fixed_version', sa.String(length=64), nullable=True),
    sa.Column('exploitability', sa.String(length=32), nullable=False),
    sa.Column('internet_exposed', sa.Boolean(), nullable=False),
    sa.Column('asset_criticality', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=16), nullable=False),
    sa.Column('is_kev', sa.Boolean(), nullable=False),
    sa.Column('ai_analysis_json', sa.Text(), nullable=False),
    sa.Column('remediation_json', sa.Text(), nullable=False),
    sa.Column('remediation_level', sa.String(length=40), nullable=False),
    sa.Column('standards_json', sa.Text(), nullable=False),
    sa.Column('references', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_change', sa.String(length=32), nullable=False),
    sa.Column('is_suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppression_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_findings_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_findings_scan_id_scans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_findings_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index(op.f('ix_findings_asset_id'), 'findings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.create_index(op.f('ix_findings_cve'), 'findings', ['cve'], unique=False)
    op.create_index(op.f('ix_findings_cwe'), 'findings', ['cwe'], unique=False)
    op.create_index(op.f('ix_findings_finding_no'), 'findings', ['finding_no'], unique=True)
    op.create_index(op.f('ix_findings_risk_band'), 'findings', ['risk_band'], unique=False)
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_index(op.f('ix_findings_tenant_id'), 'findings', ['tenant_id'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('checks_run', sa.Integer(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_scan_results_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_scan_results_scan_id_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_scan_results_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_results'))
    )
    op.create_index(op.f('ix_scan_results_scan_id'), 'scan_results', ['scan_id'], unique=False)
    op.create_index(op.f('ix_scan_results_tenant_id'), 'scan_results', ['tenant_id'], unique=False)
    op.create_table('scan_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_scan_targets_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_scan_targets_scan_id_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_scan_targets_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_targets'))
    )
    op.create_index(op.f('ix_scan_targets_scan_id'), 'scan_targets', ['scan_id'], unique=False)
    op.create_index(op.f('ix_scan_targets_tenant_id'), 'scan_targets', ['tenant_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_auto_expired', sa.Boolean(), nullable=False),
    sa.Column('compensating_control_desc', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_exceptions_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_exceptions_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_exceptions_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_exceptions_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exceptions'))
    )
    op.create_index(op.f('ix_exceptions_finding_id'), 'exceptions', ['finding_id'], unique=False)
    op.create_index(op.f('ix_exceptions_tenant_id'), 'exceptions', ['tenant_id'], unique=False)
    op.create_table('finding_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_changes_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_finding_changes_scan_id_scans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding_changes'))
    )
    op.create_index(op.f('ix_finding_changes_finding_id'), 'finding_changes', ['finding_id'], unique=False)
    op.create_table('remediations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('immediate_action', sa.Text(), nullable=False),
    sa.Column('permanent_solution', sa.Text(), nullable=False),
    sa.Column('recommended_config', sa.Text(), nullable=False),
    sa.Column('patch_recommendation', sa.Text(), nullable=False),
    sa.Column('verification_procedure', sa.Text(), nullable=False),
    sa.Column('rollback_procedure', sa.Text(), nullable=False),
    sa.Column('business_impact', sa.Text(), nullable=False),
    sa.Column('complexity', sa.String(length=32), nullable=False),
    sa.Column('risk_reduction', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backup_status', sa.String(length=64), nullable=False),
    sa.Column('execution_status', sa.String(length=32), nullable=False),
    sa.Column('verification_result', sa.Text(), nullable=False),
    sa.Column('auto_remediated', sa.Boolean(), nullable=False),
    sa.Column('audit_log_json', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_remediations_approver_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_remediations_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_remediations_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_remediations_requester_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_remediations_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remediations'))
    )
    op.create_index(op.f('ix_remediations_finding_id'), 'remediations', ['finding_id'], unique=False)
    op.create_index(op.f('ix_remediations_status'), 'remediations', ['status'], unique=False)
    op.create_index(op.f('ix_remediations_tenant_id'), 'remediations', ['tenant_id'], unique=False)
    op.create_table('approval_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remediation_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediations.id'], name=op.f('fk_approval_steps_remediation_id_remediations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_steps'))
    )
    op.create_index(op.f('ix_approval_steps_remediation_id'), 'approval_steps', ['remediation_id'], unique=False)
    op.create_table('remediation_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remediation_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_remediation_approvals_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediations.id'], name=op.f('fk_remediation_approvals_remediation_id_remediations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_remediation_approvals_tenant_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remediation_approvals'))
    )
    op.create_index(op.f('ix_remediation_approvals_remediation_id'), 'remediation_approvals', ['remediation_id'], unique=False)
    op.create_index(op.f('ix_remediation_approvals_tenant_id'), 'remediation_approvals', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_approvals_tenant_id'), table_name='remediation_approvals')
    op.drop_index(op.f('ix_remediation_approvals_remediation_id'), table_name='remediation_approvals')
    op.drop_table('remediation_approvals')
    op.drop_index(op.f('ix_approval_steps_remediation_id'), table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_index(op.f('ix_remediations_tenant_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_status'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_finding_id'), table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_finding_changes_finding_id'), table_name='finding_changes')
    op.drop_table('finding_changes')
    op.drop_index(op.f('ix_exceptions_tenant_id'), table_name='exceptions')
    op.drop_index(op.f('ix_exceptions_finding_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_scan_targets_tenant_id'), table_name='scan_targets')
    op.drop_index(op.f('ix_scan_targets_scan_id'), table_name='scan_targets')
    op.drop_table('scan_targets')
    op.drop_index(op.f('ix_scan_results_tenant_id'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_scan_id'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_findings_tenant_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_risk_band'), table_name='findings')
    op.drop_index(op.f('ix_findings_finding_no'), table_name='findings')
    op.drop_index(op.f('ix_findings_cwe'), table_name='findings')
    op.drop_index(op.f('ix_findings_cve'), table_name='findings')
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_index(op.f('ix_findings_asset_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_subdomains_tenant_id'), table_name='subdomains')
    op.drop_index(op.f('ix_subdomains_status'), table_name='subdomains')
    op.drop_index(op.f('ix_subdomains_domain_id'), table_name='subdomains')
    op.drop_table('subdomains')
    op.drop_index(op.f('ix_scans_tenant_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_scan_key'), table_name='scans')
    op.drop_index(op.f('ix_scans_requested_by'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_scan_schedules_tenant_id'), table_name='scan_schedules')
    op.drop_table('scan_schedules')
    op.drop_index(op.f('ix_reports_tenant_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_key'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('asset_group_members')
    op.drop_index(op.f('ix_vulnerabilities_tenant_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_fingerprint'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cwe'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cve'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_integrations_tenant_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_domains_tenant_id'), table_name='domains')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_is_internet_facing'), table_name='assets')
    op.drop_index(op.f('ix_assets_ip_address'), table_name='assets')
    op.drop_index(op.f('ix_assets_hostname'), table_name='assets')
    op.drop_index(op.f('ix_assets_domain'), table_name='assets')
    op.drop_index(op.f('ix_assets_department'), table_name='assets')
    op.drop_index(op.f('ix_assets_criticality'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_key'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_asset_groups_tenant_id'), table_name='asset_groups')
    op.drop_table('asset_groups')
    op.drop_table('threat_intelligence')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_cves_cve_id'), table_name='cves')
    op.drop_table('cves')
    op.drop_index(op.f('ix_compliance_mappings_standard'), table_name='compliance_mappings')
    op.drop_table('compliance_mappings')
    op.drop_index(op.f('ix_cisa_kev_cve_id'), table_name='cisa_kev')
    op.drop_table('cisa_kev')
    # ### end Alembic commands ###
